### ISSUE TITLE
fix: 하단바에 컨텐츠가 잘리는 현상

### ISSUE THREAD

**Issue by ChoEun-Sang** [FoodieLog/foodie-log-client#67]
### 이슈
- 스크롤을 다 내렸을 때, 하단탭에 내용이 잘리는 현상

### 참고
<img width="390" alt="스크린샷 2023-09-07 오전 10 42 31" src="https://github.com/FoodieLog/foodie-log-client/assets/128155681/351c4600-270a-4aaf-97d1-12ce6928a55f">

**Comment by iskra17** [comment]
하단바가 현재 fixed bottom-0 으로 지정되어 있어서 컨텐츠가 하단바 밑에 들어가서 안보이는 현상인데요.
하단바를 fixed 시키지 않고, 그냥 flex-col 의 마지막 컴포넌트로 두면서, 전체 컴포넌트를 스크린 세로에 담아야 하는데 아직 그 부분 해결을 못해서 임시로 고정해두었습니다. 이슈 확인 감사합니다!

**Comment by iskra17** [comment]
해당 이슈 해결 되었습니다. 본문(children 부분)의 하단에 padding 을 줘서 하단바와 겹치지 않게 하였습니다!
