### ISSUE TITLE
Fix: 마이페이지 및 프로필 설정 페이지 QA

### ISSUE THREAD

**Issue by chaewon12** [FoodieLog/foodie-log-client#82]
테스트 하다가 발견한 오류 입니다
확인 부탁드려요!

## 🐞 
- [ ] 마이페이지 화면 구성이 피그마와 상이함 
- [ ] 다른 사람 페이지에서도 프로필 수정 버튼이 뜸
- [ ] 프로필 설정 페이지에 자기 소개가 안뜸 
- [ ] 프로필 설정 페이지 화면 몰림? 현상

## 💡 해결 및 참고 사항
![image](https://github.com/FoodieLog/foodie-log-client/assets/65496092/18402674-9a6e-4b8e-a0c1-72693d1ef4b4)
![KakaoTalk_Photo_2023-09-11-13-46-37](https://github.com/FoodieLog/foodie-log-client/assets/65496092/d59aaadb-6e44-468d-8400-e6bc230031e1)
![KakaoTalk_Photo_2023-09-11-13-46-22](https://github.com/FoodieLog/foodie-log-client/assets/65496092/46bfe032-a310-4304-812c-073d0bee599b)

**Comment by ChoEun-Sang** [comment]
네 수정할게요!

**Comment by chaewon12** [comment]
상단바(뒤로가기 버튼이랑 닉네임이 있는 곳) 오른쪽 끝에 두면 될 것 같아요!
