### ISSUE TITLE
Fix: 나의 맛집 리스트 QA

### ISSUE THREAD

**Issue by chaewon12** [FoodieLog/foodie-log-client#83]
## 버그 및 개선점
- [x] 음식점 상세보기 페이지에서는 저장 아이콘이 [하트] -> [별]로 수정 
- [ ] 설계 시 "장소 하단 3개 정도 표시. 그리고 장소 스크롤시 장소가 5개 정도 유지하면서 스크롤 됨" 이지만 현재는 처음 한 개 표시 & 스크롤시 지도 사라짐
- [x] 지도의 마커가 어느 음식점인지 식별이 안됨. 거능하다면 마커 밑에 음식점 이름 표시
- [x] 다른 사람의 프로필-지도로 보기 클릭 시 나의 맛집 리스트가 뜸
       -> 1. 저장한 맛집 리스트와 피드 지도로 보기의 구분이 필요함. 현재는 둘 다 이름이 "나의 맛집 리스트"임
            2. 다른 사람 지도로 보기가 떠야하는데 내 지도로 보기가 뜸

## 그외 질문
1. 마커 클릭 이벤트는 없나요? 
클릭 이벤트가 없다면 
지도로 음식점 위치를 확인한 후 음식점 상세페이지를 보려면
리스트를 내려서 다시 찾아야하는 번거로움 존재 

## 참고 
- 맛집 리스트 페이지와 맛집 상세보기 페이지의 저장 아이콘이 다름
<img width="196" alt="image" src="https://github.com/FoodieLog/foodie-log-client/assets/65496092/989e5b75-400e-43bd-a2cc-76685fbe145d">
<img width="196" alt="image" src="https://github.com/FoodieLog/foodie-log-client/assets/65496092/67fd4035-1dd5-4af5-ad00-ae0947604c7d">

- 네이버 지도의 경우 지도 줌이 "시"인 경우 마커만 보이고 "구"로 확대하면 음식점 이름이 표시
<img width="196" alt="image" src="https://github.com/FoodieLog/foodie-log-client/assets/65496092/5ebe529d-67cc-4387-b6b1-e7157bd40a02">
<img width="196" alt="image" src="https://github.com/FoodieLog/foodie-log-client/assets/65496092/83f279f8-eee7-4bd1-be8a-234be365ae28">

**Comment by ChoEun-Sang** [comment]
마커 클릭 이벤트 깜빡했습니다~ 추가할게용

**Comment by iskra17** [comment]
오 디테일한 체크 감사합니다 채원님!!!
