### ISSUE TITLE
Fix: 마이페이지 QA

### ISSUE THREAD

**Issue by inyoung0215** [FoodieLog/foodie-log-client#92]
## 버그 및 개선점
- [x] 마이페이지에서 최신순으로 피드 정렬이 되지 않음. 가장 최신 피드가 맨앞에 와야함.
- [ ] #93

## 참고
<img width="196" alt="image" src="https://github.com/FoodieLog/foodie-log-client/assets/86757234/875dfbce-80a4-4a1c-bf59-9c88e5484c47">
<img width="196" alt="image" src="https://github.com/FoodieLog/foodie-log-client/assets/86757234/9481f22b-ecac-4ecd-aaf5-ca0bec69e8b9">

**Comment by ChoEun-Sang** [comment]
@iskra17 재현님 해당 피드로 이동 부탁드립니다 🙏🏻
